name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ] #, macos-latest, windows-latest ]
        toolchain:
          - nightly
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Rustup update
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

        # if we ever need a c compiler under windows
#      - name: Run tests (windows)
#        if: matrix.platform == 'windows-latest'
#        run: |
#          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
#          cargo test --verbose
#        shell: cmd
